const
  gsTaurusTLSVersionMajor = 1;
  {$NODEFINE gsTaurusTLSVersionMajor}
  gsTaurusTLSVersionMinor = 0;
  {$NODEFINE gsTaurusTLSVersionMinor}
  gsTaurusTLSVersionRelease = 10;
  {$NODEFINE gsTaurusTLSVersionRelease}
  gsTaurusTLSVersionBuild = 52;
  {$NODEFINE gsTaurusTLSVersionBuild}

  (*$HPPEMIT '#define gsTaurusTLSVersionMajor 1'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionMinor 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionRelease 10'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionBuild 52'*)
  (*$HPPEMIT ''*)

  gsTaurusTLSVersion = '1.0.10.52'; {do not localize}
  gsTaurusTLSProductName = 'TaurusTLS';  {do not localize}
  gsTaurusTLSProductVersion = '1.0.10.52'; {do not localize}
