const
  gsTaurusTLSVersionMajor = 1;
  {$NODEFINE gsTaurusTLSVersionMajor}
  gsTaurusTLSVersionMinor = 0;
  {$NODEFINE gsTaurusTLSVersionMinor}
  gsTaurusTLSVersionRelease = 4;
  {$NODEFINE gsTaurusTLSVersionRelease}
  gsTaurusTLSVersionBuild = 41;
  {$NODEFINE gsTaurusTLSVersionBuild}

  (*$HPPEMIT '#define gsTaurusTLSVersionMajor 1'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionMinor 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionRelease 4'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionBuild 41'*)
  (*$HPPEMIT ''*)

  gsTaurusTLSVersion = '1.0.4.41'; {do not localize}
  gsTaurusTLSProductName = 'TaurusTLS';  {do not localize}
  gsTaurusTLSProductVersion = '1.0.4.41'; {do not localize}
