const
  gsTaurusTLSVersionMajor = 1;
  {$NODEFINE gsTaurusTLSVersionMajor}
  gsTaurusTLSVersionMinor = 0;
  {$NODEFINE gsTaurusTLSVersionMinor}
  gsTaurusTLSVersionRelease = 3;
  {$NODEFINE gsTaurusTLSVersionRelease}
  gsTaurusTLSVersionBuild = 40;
  {$NODEFINE gsTaurusTLSVersionBuild}

  (*$HPPEMIT '#define gsTaurusTLSVersionMajor 1'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionMinor 0'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionRelease 3'*)
  (*$HPPEMIT '#define gsTaurusTLSVersionBuild 40'*)
  (*$HPPEMIT ''*)

  gsTaurusTLSVersion = '1.0.3.40'; {do not localize}
  gsTaurusTLSProductName = 'TaurusTLS';  {do not localize}
  gsTaurusTLSProductVersion = '1.0.3.40'; {do not localize}
